
#ifndef _CTL_MODEL_CTL_H
#define _CTL_MODEL_CTL_H

/*各个模块*/
#define INC_NET_REPOERT_MODEL
#define INC_NET_CTL_MODEL

#define INC_CAPTURE_MODEL
#define INC_FILTER_MODEL
#define INC_ANALYZE_MODEL
#define INC_FLOW_STAT_ANALYSIS_MODEL
#define INC_NTP_SEVER_MODEL
#define INC_SQ_SEVER_MODEL
#define INC_DC_SERVER_MODEL 
#define INC_HW_MOT_MODEL
#define INC_BLOCK_SERVER_MODEL
#define INC_UDP_SERVER_MODEL
#define INC_CONNECT_SERVER_MODEL
#define WITH_FILE_REG_RES
#define WITH_PRINT_ITF_PAR
#define WITH_SHM_KEY_FILE

/*运行模式*/
#define RUN_WITH_DAEMON_MODEL 

/*是否调试打印*/
#define _DEBUG
#define _INFO

#undef INC_NET_REPOERT_MODEL
#undef INC_NET_CTL_MODEL

//#undef INC_CAPTURE_MODEL
//#undef INC_FILTER_MODEL
//#undef INC_ANALYZE_MODEL
//#undef INC_SQ_SEVER_MODEL
//#undef INC_NTP_SEVER_MODEL

//#undef INC_HW_MOT_MODEL
#undef INC_FLOW_STAT_ANALYSIS_MODEL
#undef WITH_PRINT_ITF_PAR
#undef WITH_SHM_KEY_FILE

#undef RUN_WITH_DAEMON_MODEL 
#endif
